name: Java Spring Boot CI for SoftClick_data
run-name: ${{ github.actor }} opened/reopened a pull request to ${{ github.base_ref }} from ${{ github.head_ref }}
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
      - develop
      - releases/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_QA_URL }}
          DATASOURCE_USER: ${{ secrets.DATASOURCE_QA_USER }}
          DATASOURCE_PWD: ${{ secrets.DATASOURCE_QA_PWD }}
          HIBERNATE_DDL_AUTO: create
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*.jar staging